remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme # Add this line if you already have a plugins list

gem "github-pages", group: :jekyll_plugins

title: "CRISP-DM"
description: "unraveling the mysteries of data understanding, modeling, and deployment"
show_downloads: true # Set to false if you don't want a download link
google_analytics: UA-XXXXXXXXX-X # Your Google Analytics tracking ID

